site_title = "ME Arxiv Daily"
limit_days = 7
#cache_url = "https://arxiv.alongwy.top/cache.json"

[[sources]]
limit = 20
category = "hep-ex"
title = "High Energy Physics - Experimental"

[[sources]]
limit = 20
category = "hep-ph"
title = "High Energy Physics - Phenomenology"

[[sources]]
limit = 20
category = "stat.ML"
title = "Machine Learning - Statistics"

[[sources]]
limit = 20
category = "cs.LG"
title = "Machine Learning - Computer Science"

[[sources]]
limit = 20
category = "cs.PL"
title = "Programming Languages"



[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
