site_title = "ME Arxiv Daily"
limit_days = 14
#cache_url = "https://arxiv.alongwy.top/cache.json"

[[sources]]
limit = 100
category = "hep-ex"
title = "High Energy Physics - Experimental"

[[sources]]
limit = 100
category = "hep-ph"
title = "High Energy Physics - Phenomenology"

[[sources]]
limit = 1
category = "cs.LG"
title = "Machine Learning"



[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
